products/urls.py
from django.urls import path, include
from .views import BrandDetail, BrandList, ProductList, ProductDetail, CategoryList, prodcut_list
from . import api
app_name = 'products'
from rest_framework import routers
router = routers.DefaultRouter()
router.register('all-products',api.ProductViewSetsAPI)
app_name = 'products'


urlpatterns = [
    path('' , ProductList.as_view() , name='product_list'),
    path('<int:pk>/',ProductDetail.as_view() , name='product_detail' ),
    path('brands/' , BrandList.as_view() , name='brand_list'),
    path('brands/<int:pk>/',BrandDetail.as_view() , name='brand_detail' ),
    path('category/',CategoryList.as_view(),name = 'category_list'),
    path('testing/', prodcut_list  ),

    path('api/products/<int:pk>',api.ProductDetailAPI.as_view()),
    path('api/products/',api.ProductListAPI.as_view()),
    path('api/brand/', api.BrandListAPI.as_view()),
    path('api/brand/<int:pk>', api.BrandDetailAPI.as_view()),
    path('api/category/',api.CategoryListAPI.as_view()),
    path('api/category/<int:pk>',api.CategoryDetailAPI.as_view()),

    path('api/', include(router.urls))

]

project/urls.py
from itertools import product
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/' , include('products.urls', namespace = 'products')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/models.py
from email.policy import default
from itertools import count
from msilib.schema import Class
from operator import imod
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator , MinValueValidator
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.db.models.aggregates import Count
# Create your models here.


FLAG_OPTION = (
    ('New','New'),
    ('Feature','Feature'),
    ('Sale','Sale'),
)


class Product(models.Model):
    name = models.CharField(max_length=100 , verbose_name=_("Name"))
    subtitle = models.CharField(_("Subtitle"),max_length=500)
    sku = models.IntegerField(_("SKU"))
    image = models.ImageField(_("Image"), upload_to='products/product_images/')
    desc = models.TextField(_("Description"),max_length=10000)
    price = models.FloatField(_("Price"))
    flag = models.CharField(_("Flag") , max_length=10 , choices=FLAG_OPTION)
    quantity = models.IntegerField(_("Quantity")) 
    brand = models.ForeignKey('Brand', verbose_name=_('Brand'), related_name='product_brand', on_delete=models.SET_NULL , null = True , blank=True )
    category = models.ForeignKey('Category', verbose_name='Category' , related_name='product_category' , on_delete=models.SET_NULL , null = True , blank=True ) 
    tags = TaggableManager()
    # add slug to url 
    slug = models.SlugField(_("Slug"),null=True , blank= True)
    
      
    def __str__(self):
        return self.name

    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product,self).save(*args, **kwargs)


    

    



class ProductImages(models.Model):
    product = models.ForeignKey( Product, related_name='product_image', on_delete=models.CASCADE, verbose_name=_("Product"))
    image  = models.ImageField(_("Image"), upload_to='products/product_images/')


    def __str__(self):
        return str(self.product)




class Brand(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    image = models.ImageField(_("Image"), upload_to ='products/brands/')
    category = models.ForeignKey('Category', related_name='brand_category', verbose_name=_('Category'),on_delete=models.CASCADE )

    def __str__(self):
        return self.name

    def product_count(self):
        return self.product_brand.aggregate(my_count = Count('brand'))
        



class Category(models.Model):
    name= models.CharField(_("Name") ,max_length=50  )
    image = models.ImageField(_("Image"), upload_to ='products/category/')

    def __str__(self):
        return self.name




class ProductReview(models.Model):
    user = models.ForeignKey(User, related_name='user_review', on_delete=models.CASCADE, verbose_name=_("User") )
    product = models.ForeignKey(Product, related_name='product_review', on_delete=models.CASCADE, verbose_name=_("Product"))
    rate = models.IntegerField(_("Rate"),validators=[MaxValueValidator(5),MinValueValidator(0)] )
    review  = models.CharField(_("Review"), max_length=500 )
    created_at = models.DateTimeField(verbose_name=_("Created_At"),default=timezone.now)


    def __str__(self):
        return str(self.user )+'Review on ' + str(self.product)

products/views.py
from __future__ import annotations
from itertools import product
from multiprocessing import get_context
from unicodedata import category
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product ,Brand, Category ,ProductImages 
from django.db.models.aggregates import Count
from django.db.models import Value ,F
from django.core.paginator import Paginator

# Create your views here.

# Function Based View
def prodcut_list(request):
    # products = Product.objects.all()                                  # All products with out filter
    # products = Product.objects.filter(price__lte = 50 )               # greater than or equal 
    # products = Product.objects.filter(price__gte = 50 )               # less than or equal
    # products = Product.objects.filter(price__gt = 50 )                # greater than
    # products = Product.objects.filter(price__lt = 50 )                # less than
    
    products = Product.objects.filter(price__gt = 50 )

    # Show 25 products per page.
    paginator = Paginator(products, 25) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    return render(request, 'products/product_list_test.html', { 'products':products , 'page_obj': page_obj })

# Class Based View  
class ProductList(ListView):
    model = Product
    paginate_by = 24
    # ListView ^-^
    # context  -> product_list or object_list
    # templete -> must named -> product_list.html 

class ProductDetail(DetailView):
    model= Product

    # DetailView ^-^
    # context  -> product_detail or object_detail
    # templete -> must named -> product_detail.html 


class BrandList(ListView):
    model = Brand
   

    # override get_context_data with other context  
    def get_context_data(self, **kwargs):
        # we use super() funtion to run the two methods -first in ListView, -second on BrandList ( in this class )
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all
        # select_related() to prevent doing more queirs for each category 
        context["brand_list"] = Brand.objects.select_related('category').all().annotate(
            product_count=Count('product_brand'))
        return context
    


class BrandDetail(DetailView):
    model = Brand 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        brand = self.get_object()
        context['product_brand'] = Product.objects.filter(brand=brand)
        context['number'] = brand.product_count()
        return context
    


class CategoryList(ListView):
    model = Category
    

products/templates/products/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="css/brand-list.css">
{% endblock css %}

{% block body %}
    <!--=====================================
                        PRODUCT VIEW START
            =======================================-->
    <div class="modal fade" id="product-view">
        <div class="modal-dialog">
            <div class="modal-content">
                <button class="modal-close icofont-close" data-bs-dismiss="modal"></button>
                <div class="product-view">
                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <div class="view-gallery">
                                <div class="view-label-group">
                                    <label class="view-label new">new</label>
                                    <label class="view-label off">-10%</label>
                                </div>
                                <ul class="preview-slider slider-arrow">
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                </ul>
                                <ul class="thumb-slider">
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                    <li><img src="images/product/01.jpg" alt="product"></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="view-details">
                                <h3 class="view-name">
                                    <a href="product-video.html">existing product name</a>
                                </h3>
                                <div class="view-meta">
                                    <p>SKU:<span>1234567</span></p>
                                    <p>BRAND:<a href="#">radhuni</a></p>
                                </div>
                                <div class="view-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3 reviews)</a>
                                </div>
                                <h3 class="view-price">
                                    <del>$38.00</del>
                                    <span>$24.00<small>/per kilo</small></span>
                                </h3>
                                <p class="view-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit non tempora
                                    magni repudiandae sint suscipit tempore quis maxime explicabo veniam eos reprehenderit
                                    fuga</p>
                                <div class="view-list-group">
                                    <label class="view-list-title">tags:</label>
                                    <ul class="view-tag-list">
                                        <li><a href="#">organic</a></li>
                                        <li><a href="#">vegetable</a></li>
                                        <li><a href="#">chilis</a></li>
                                    </ul>
                                </div>
                                <div class="view-list-group">
                                    <label class="view-list-title">Share:</label>
                                    <ul class="view-share-list">
                                        <li><a href="#" class="icofont-facebook" title="Facebook"></a></li>
                                        <li><a href="#" class="icofont-twitter" title="Twitter"></a></li>
                                        <li><a href="#" class="icofont-linkedin" title="Linkedin"></a></li>
                                        <li><a href="#" class="icofont-instagram" title="Instagram"></a></li>
                                    </ul>
                                </div>
                                <div class="view-add-group">
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add to cart</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i
                                                class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity"
                                            value="1">
                                        <button class="action-plus" title="Quantity Plus"><i
                                                class="icofont-plus"></i></button>
                                    </div>
                                </div>
                                <div class="view-action-group">
                                    <a class="view-wish wish" href="#" title="Add Your Wishlist">
                                        <i class="icofont-heart"></i>
                                        <span>add to wish</span>
                                    </a>
                                    <a class="view-compare" href="compare.html" title="Compare This Item">
                                        <i class="fas fa-random"></i>
                                        <span>Compare This</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--=====================================
                        PRODUCT VIEW END
            =======================================-->


    <!--=====================================
                        BANNER PART START
            =======================================-->
    <section class="inner-section single-banner" style="background: url({% static 'images/single-banner.jpg' %}) no-repeat center;">
        <div class="container">
            <h2>brand list</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">brand-list</li>
            </ol>
        </div>
    </section>
    <!--=====================================
                        BANNER PART END
            =======================================-->


    <!--=====================================
                        BRAND LIST PART START
            =======================================-->
            <section class="inner-section">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="top-filter">
                                <div class="filter-show">
                                    <label class="filter-label">Show :</label>
                                    <select class="form-select filter-select">
                                        <option value="1">12</option>
                                        <option value="2">24</option>
                                        <option value="3">36</option>
                                    </select>
                                </div>

                                <div class="filter-short">
                                    <label class="filter-label">Short by :</label>
                                    <select class="form-select filter-select isotope-select">
                                        <option value="*">show all</option>
                                        {% for category in categories  %}
                                        <option value=".{{ category|cut:' '|cut:'.' }}">{{category.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                        {% for brand in brand_list  %}
                        <div class="col all {{brand.category|cut:' '|cut:'.'}}">
                            <div class="brand-wrap">
                                <div class="brand-media">
                                    <img src="{{brand.image.url}}" alt="brand">
                                    <div class="brand-overlay">
                                        <a href="{% url 'products:brand_detail' brand.id %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>

                                <div class="brand-meta">
                                    <h4>{{brand}}</h4>
                                    <p>({{brand.product_count}} items)</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a class="page-link" href="#">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item">...</li>
                                    <li class="page-item"><a class="page-link" href="#">60</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

    <!--=====================================
                        BRAND LIST PART END
            =======================================-->
{% endblock body %}


{% block CSS-brand_list %}
<script src="{% static 'vendor/isotope/isotope.pkgd.min.js' %} "></script>
<script src="{% static 'js/isotope.js' %} "></script>
{% endblock CSS-brand_list %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


    
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url({% static 'images/single-banner.jpg' %})    no-repeat center;">
            <div class="container">
                <h2>Shop</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Shop</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="{{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</option>
                                    <option value="{{ page_obj.paginator.num_pages }}">24</option>
                                    <option value="{{ page_obj.paginator.num_pages }}">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                            <div class="filter-action">
                                <a href="shop-3column.html" title="Three Column"><i class="fas fa-th"></i></a>
                                <a href="shop-2column.html" title="Two Column"><i class="fas fa-th-large"></i></a>
                                <a href="shop-1column.html" title="One Column"><i class="fas fa-th-list"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">

                    
                    {% for product in object_list %}            
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{product.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href=" {% url 'products:product_detail' product.id %}">
                                    <img src="{{product.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(4)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="{% url 'products:product_detail' product.id %}">{{product}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <del>$34</del>
                                    <span>${{product.price}}<small>/piece</small></span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">

                            <p class="page-info">Showing 24 of {{page_obj.paginator.count}} Results</p>
                            
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li> <i class="fas fa-long-arrow-alt-left"></i></li>
                                {% endif %}

                                {% for i in paginator.page_range  %}
                                    {% if page_obj.number == i  %} 
                                        {% if page_obj.has_previous and page_obj.previous_page_number > 1  %}
                                            <li class="page-item"><a class="page-link" href="?page={{i|add:'-2'}}">{{i|add:"-2"}}</a></li>
                                            <li class="page-item"><a class="page-link" href="?page={{i|add:'-1'}}">{{i|add:"-1"}}</a></li>
                                        {% endif %}
                                        <li class="page-item"><a class="page-link active" href="?page={{i}}">{{i}}</a></li>
                                        {% if page_obj.has_next %}
                                            {% if page_obj.has_next and page_obj.next_page_number < page_obj.paginator.num_pages %}
                                                <li class="page-item"><a class="page-link" href="?page={{i|add:'+1'}}">{{i|add:"+1"}}</a></li>
                                                {% if page_obj.number < page_obj.paginator.num_pages|add:'-2'  %}
                                                    <li class="page-item">...</li>
                                                {% endif %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages}}</a>
                                                </li>
                                             {% endif %}
                                         {% endif %}
                                   {% endif %}
                                {% endfor %}
                                

                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                        <i class="fas fa-long-arrow-alt-right "></i>
                                    </a>
                                </li>
                                {% else %}
                                 <li><i class="fas fa-long-arrow-alt-right disabled"></i></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
        {% endblock body %}

products/templates/products/product_list_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>testing</title>
</head>
<body>
    <ul>
        {% for product in products %}
        <li>{{product}} - {{product.price}}$ </li>
        {% endfor %}
    </ul>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1"> &laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>